### PR TITLE
fix missing header

### LINKED ISSUE #6: Header is missing.
The header in the auth page is missing.

### PR DESCRIPTION
**Pull request by jelgun**
bug fixed

### CODE REVIEW

File: frontend/src/components/auth/Auth.vue [hunk 1]
```diff
@@ -1,5 +1,6 @@
 <template>
    <v-container class="mx-auto px-4">
+      <h1 class="text-center">Todo App</h1>
```
Comment (dijitalYoruk) [inline frontend/src/components/auth/Auth.vue]: The header should be "Awesome Todo Application"

Comment (jelgun) [reply frontend/src/components/auth/Auth.vue]: Sure, I will fix it.

**Comment by dijitalYoruk** [comment]
You can merge it.
